### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by IgorGanapolsky** [spengilley/AndroidMVPTemplate#1]
I get an error:
Error:Execution failed for task ':app:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_40\bin\java.exe'' finished with non-zero exit value 1

**Comment by spengilley** [comment]
Hi there,

I have been unable to duplicate your problem. Incidentally I have updated the project to be compatible with current gradle versions. Try updating the project and see how you get on. If not, Google searches may reveal the answer

**Comment by IgorGanapolsky** [comment]
I have all the latest and greatest - Android Studio beta, gradle, android sdk, Java 8.  Some of your dependencies in build.gradle were very outdated.  I updated them to the latest versions, but still no dice.

**Comment by spengilley** [comment]
Sounds like you did everything right. No idea why you are receiving this error.

**Comment by yukihane** [comment]
I get same error, on OracleJDK8:
<pre>
$ gradle :app:preDexDebug
(snip)
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:704)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
...while parsing com/spengilley/MVPTemplate/preferences/PreferencesModule$$ModuleAdapter.class
1 error; aborting

:app:preDexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1
</pre>

And fix:
<pre>
diff --git a/build.gradle b/build.gradle
index 61288fc..17e476a 100644
--- a/build.gradle
+++ b/build.gradle
@@ -5,7 +5,7 @@ buildscript {
         jcenter()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:1.1.3'
+        classpath 'com.android.tools.build:gradle:1.2.3'
 
         // NOTE: Do not place your application dependencies here; they belong
         // in the individual module build.gradle files
diff --git a/core/build.gradle b/core/build.gradle
index 5faf02f..e15c009 100644
--- a/core/build.gradle
+++ b/core/build.gradle
@@ -1,5 +1,7 @@
 apply plugin: 'java'
 
+sourceCompatibility = JavaVersion.VERSION_1_7
+
 repositories {
     mavenCentral()
 }
</pre>

**Comment by maoruibin** [comment]
I meet same error , I have a try to google but not find right answer 
Error:Execution failed for task ':app:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

**Comment by IgorGanapolsky** [comment]
Clean build folders.  Rebuild.
